# Generated by GitHub Copilot – follow project guidelines above
"""
Sentinel alert to ECS mapping module.

This module provides mapper classes for transforming Microsoft Sentinel alert evidence
into Elastic Common Schema (ECS) format for storage in Howler.
"""
