# Generated by GitHub Copilot – follow project guidelines above
"""
Main orchestrator for mapping Sentinel alerts to ECS format.

This module provides the central orchestration logic for transforming
Microsoft Sentinel alerts into ECS-compliant hits for storage in Howler.
"""

import uuid
import hashlib
from typing import Any, Dict, List, Optional, Tuple
from datetime import datetime

from howler.common.logging import get_logger
from howler.odm.models.hit import Hit
from howler.odm.models.howler_data import HowlerData

from sentinel.mappers.base import evidence_mapper_registry, BaseMapper, MappingError
from sentinel.mappers.device import DeviceEvidenceMapper
from sentinel.mappers.process import ProcessEvidenceMapper
from sentinel.mappers.user import UserEvidenceMapper
from sentinel.mappers.file import FileEvidenceMapper
from sentinel.mappers.ip import IpEvidenceMapper
from sentinel.mappers.url import UrlEvidenceMapper
from sentinel.mappers.registry import RegistryKeyEvidenceMapper, RegistryValueEvidenceMapper
from sentinel.mappers.cloud import CloudApplicationEvidenceMapper, OAuthApplicationEvidenceMapper

logger = get_logger(__file__)


class SentinelAlertMapper:
    """
    Main orchestrator for mapping Sentinel alerts to ECS format.
    
    This class coordinates the mapping of Sentinel alert data and evidence
    to create ECS-compliant hit objects suitable for storage in Howler.
    """
    
    def __init__(self) -> None:
        self.logger = get_logger(self.__class__.__module__)
        self._initialize_mappers()
    
    def _initialize_mappers(self) -> None:
        """Initialize and register evidence mappers."""
        # Register mappers for different evidence types
        evidence_mapper_registry.register(
            "#microsoft.graph.security.deviceEvidence", 
            DeviceEvidenceMapper()
        )
        evidence_mapper_registry.register(
            "#microsoft.graph.security.processEvidence", 
            ProcessEvidenceMapper()
        )
        evidence_mapper_registry.register(
            "#microsoft.graph.security.userEvidence", 
            UserEvidenceMapper()
        )
        evidence_mapper_registry.register(
            "#microsoft.graph.security.fileEvidence", 
            FileEvidenceMapper()
        )
        # Register new evidence mappers
        evidence_mapper_registry.register(
            "#microsoft.graph.security.ipEvidence", 
            IpEvidenceMapper()
        )
        evidence_mapper_registry.register(
            "#microsoft.graph.security.urlEvidence", 
            UrlEvidenceMapper()
        )
        evidence_mapper_registry.register(
            "#microsoft.graph.security.registryKeyEvidence", 
            RegistryKeyEvidenceMapper()
        )
        evidence_mapper_registry.register(
            "#microsoft.graph.security.registryValueEvidence", 
            RegistryValueEvidenceMapper()
        )
        evidence_mapper_registry.register(
            "#microsoft.graph.security.cloudApplicationEvidence", 
            CloudApplicationEvidenceMapper()
        )
        evidence_mapper_registry.register(
            "#microsoft.graph.security.oauthApplicationEvidence", 
            OAuthApplicationEvidenceMapper()
        )
        
        self.logger.info(
            "Initialized Sentinel mappers for evidence types: %s",
            ", ".join(evidence_mapper_registry.get_supported_types())
        )
    
    def map_alert(self, sentinel_alert: Dict[str, Any]) -> Tuple[Dict[str, Any], List[str]]:
        """
        Map a Sentinel alert to a dictionary format for API compatibility.
        
        Args:
            sentinel_alert: Complete Sentinel alert data
            
        Returns:
            Tuple of (hit dictionary, list of warnings/errors)
        """
        # Validate input data
        if not isinstance(sentinel_alert, dict):
            warning = f"Invalid alert data type: {type(sentinel_alert)}. Expected dict."
            self.logger.error(warning)
            return self._create_minimal_hit_dict(), [warning]
        
        try:
            hit, warnings = self.map_alert_to_hit(sentinel_alert)
            
            # Convert Hit object to dictionary
            hit_dict = hit.as_primitives()
            return hit_dict, warnings
            
        except Exception as e:
            error_msg = f"Failed to map alert: {str(e)}"
            self.logger.error(error_msg)
            
            # Create safe fallback hit
            fallback_hit = self._create_minimal_hit_dict(sentinel_alert.get('id') if isinstance(sentinel_alert, dict) else None)
            return fallback_hit, [error_msg]
    
    def _create_minimal_hit_dict(self, alert_id: Optional[str] = None) -> Dict[str, Any]:
        """
        Create a minimal hit dictionary for fallback scenarios.
        
        Args:
            alert_id: Optional alert ID to include
            
        Returns:
            Minimal hit dictionary structure
        """
        return {
            'howler': {
                'id': str(uuid.uuid4()),
                'analytic': 'sentinel.alert',
                'hash': hashlib.sha256(f"fallback-{uuid.uuid4()}".encode()).hexdigest(),
                'score': 0,
                'escalation': 'alert',
                'assignment': 'unassigned',
                'status': 'open'
            },
            'event': {
                'id': alert_id or 'unknown',
                'kind': 'alert',
                'category': ['security']
            },
            '@timestamp': datetime.utcnow().isoformat() + 'Z'
        }
    
    def map_alert_to_hit(self, sentinel_alert: Dict[str, Any]) -> Tuple[Hit, List[str]]:
        """
        Map a complete Sentinel alert to an ECS hit with fault tolerance.
        
        Args:
            sentinel_alert: Complete Sentinel alert data
            
        Returns:
            Tuple of (ECS-compliant Hit object, list of warnings/errors)
            
        Raises:
            MappingError: Only if critical mandatory fields are missing
        """
        warnings: List[str] = []
        
        # Validate input
        if not isinstance(sentinel_alert, dict):
            raise MappingError(f"Invalid alert data type: {type(sentinel_alert)}. Expected dict.")
        
        try:
            # Create base hit with alert metadata
            hit, base_warnings = self._create_base_hit_safe(sentinel_alert)
            warnings.extend(base_warnings)
            
            # Process evidence items with fault tolerance
            evidence_list = sentinel_alert.get('evidence', [])
            if not evidence_list:
                warning = f"Sentinel alert {hit.howler.id} has no evidence items"
                warnings.append(warning)
                self.logger.warning(warning)
            else:
                hit, evidence_warnings = self._process_evidence_list(evidence_list, hit)
                warnings.extend(evidence_warnings)
            
            # Add final validation and cleanup
            validation_warnings = self._finalize_hit_safe(hit, sentinel_alert)
            warnings.extend(validation_warnings)
            
            self.logger.info(
                "Successfully mapped Sentinel alert %s to hit with %d evidence items, %d warnings",
                hit.howler.id,
                len(evidence_list) if isinstance(evidence_list, list) else 0,
                len(warnings)
            )
            
            return hit, warnings
            
        except Exception as e:
            alert_id = sentinel_alert.get('id', 'unknown') if isinstance(sentinel_alert, dict) else 'unknown'
            error_msg = f"Critical failure mapping Sentinel alert {alert_id}: {str(e)}"
            self.logger.error(error_msg)
            raise MappingError(error_msg) from e
    
    def _create_base_hit_safe(self, sentinel_alert: Dict[str, Any]) -> Tuple[Hit, List[str]]:
        """
        Create base hit object from Sentinel alert metadata with error resilience.
        
        Args:
            sentinel_alert: Sentinel alert data
            
        Returns:
            Tuple of (Hit object with base fields populated, list of warnings)
        """
        warnings: List[str] = []
        
        try:
            # Generate hash for the alert - handle None alert ID
            alert_id = sentinel_alert.get('id')
            if alert_id is None:
                alert_id = 'unknown'
                warnings.append("Alert ID is None, using 'unknown'")
            elif not isinstance(alert_id, str):
                alert_id = str(alert_id)
                warnings.append(f"Alert ID is not a string, converted to: {alert_id}")
            
            hash_input = f"sentinel-alert-{alert_id}-{datetime.utcnow().isoformat()}"
            alert_hash = hashlib.sha256(hash_input.encode()).hexdigest()
            
            # Create hit with all required fields
            hit_data = {
                'howler': {
                    'id': str(uuid.uuid4()),
                    'analytic': 'sentinel.alert',
                    'hash': alert_hash,
                    'score': 0,
                    'escalation': 'alert',
                    'assignment': 'unassigned',
                    'status': 'open'
                },
                'event': {
                    'id': alert_id,
                    'kind': 'alert'
                },
                '@timestamp': datetime.utcnow().isoformat() + 'Z'
            }
            
            # Create hit object
            hit = Hit(hit_data)
            
            # Set optional alert metadata safely
            try:
                alert_display_name = sentinel_alert.get('alertDisplayName')
                if alert_display_name is not None:
                    if not isinstance(alert_display_name, str):
                        alert_display_name = str(alert_display_name)
                        warnings.append("Alert display name is not a string, converted")
                else:
                    alert_display_name = 'Sentinel Alert'
                    warnings.append("Alert display name is None, using default")
                
                if hasattr(hit, 'rule'):
                    hit.rule = {'name': alert_display_name}
                    
                description = sentinel_alert.get('description')
                if description is not None and isinstance(description, str) and description.strip():
                    if hasattr(hit.rule, 'description'):
                        hit.rule['description'] = description
                elif description is not None and not isinstance(description, str):
                    warnings.append("Description is not a string, ignoring")
                    
                # Add tags for categorization
                hit.tags = []
                
                severity = sentinel_alert.get('severity')
                if severity is not None:
                    if isinstance(severity, str) and severity.strip():
                        hit.tags.append(f"severity:{severity.lower()}")
                    else:
                        warnings.append("Severity is not a valid string, ignoring")
                    
                status = sentinel_alert.get('status')
                if status is not None:
                    if isinstance(status, str) and status.strip():
                        hit.tags.append(f"status:{status.lower()}")
                    else:
                        warnings.append("Status is not a valid string, ignoring")
                    
            except Exception as e:
                warnings.append(f"Failed to set optional metadata: {str(e)}")
                
        except Exception as e:
            error_msg = f"Critical error creating base hit: {str(e)}"
            warnings.append(error_msg)
            self.logger.error(error_msg)
            raise MappingError(error_msg) from e
        
        return hit, warnings
    
    def _process_evidence_list(self, evidence_list: List[Dict[str, Any]], hit: Hit) -> Tuple[Hit, List[str]]:
        """
        Process all evidence items and map them to the hit with fault tolerance.
        
        Args:
            evidence_list: List of evidence items from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Tuple of (updated hit object, list of warnings/errors)
        """
        evidence_stats: Dict[str, int] = {}
        warnings: List[str] = []
        successful_mappings = 0
        
        # Validate evidence_list is actually a list
        if not isinstance(evidence_list, list):
            warning = f"Evidence list is not a list (type: {type(evidence_list)}), skipping evidence processing"
            warnings.append(warning)
            self.logger.warning(warning)
            return hit, warnings
        
        for i, evidence_item in enumerate(evidence_list):
            try:
                # Validate evidence item structure
                if not isinstance(evidence_item, dict):
                    warning = f"Evidence item {i} is not a dictionary, skipping"
                    warnings.append(warning)
                    self.logger.warning(warning)
                    continue
                
                odata_type = evidence_item.get('@odata.type')
                if not odata_type:
                    warning = f"Evidence item {i} missing @odata.type field"
                    warnings.append(warning)
                    self.logger.warning(warning)
                    continue
                
                # Get appropriate mapper
                mapper = evidence_mapper_registry.get_mapper(odata_type)
                if not mapper:
                    warning = f"No mapper available for evidence type: {odata_type}"
                    warnings.append(warning)
                    self.logger.warning(warning)
                    continue
                
                # Apply mapping with error isolation
                try:
                    hit = mapper.map(evidence_item, hit)
                    successful_mappings += 1
                    evidence_stats[odata_type] = evidence_stats.get(odata_type, 0) + 1
                    
                    self.logger.debug(
                        "Successfully mapped evidence %d of type %s", 
                        i, odata_type
                    )
                    
                except MappingError as e:
                    warning = f"Failed to map evidence item {i} ({odata_type}): {str(e)}"
                    warnings.append(warning)
                    self.logger.error(warning)
                    continue
                    
                except Exception as e:
                    warning = f"Unexpected error mapping evidence item {i} ({odata_type}): {str(e)}"
                    warnings.append(warning)
                    self.logger.error(warning)
                    continue
                
            except Exception as e:
                warning = f"Critical error processing evidence item {i}: {str(e)}"
                warnings.append(warning)
                self.logger.error(warning)
                continue
        
        # Log evidence processing summary
        self.logger.info(
            "Evidence processing complete: %d/%d successful mappings across %d types",
            successful_mappings, len(evidence_list), len(evidence_stats)
        )
        
        if evidence_stats:
            self.logger.debug("Evidence mapping summary: %s", evidence_stats)
        
        # Finalize process mapping to ensure complete hierarchy
        try:
            self._finalize_process_mapping(hit)
        except Exception as e:
            warning = f"Failed to finalize process mapping: {str(e)}"
            warnings.append(warning)
            self.logger.warning(warning)
        
        return hit, warnings
    
    def _finalize_hit_safe(self, hit: Hit, sentinel_alert: Dict[str, Any]) -> List[str]:
        """
        Perform final validation and cleanup on the hit with error resilience.
        
        Args:
            hit: Hit object to finalize
            sentinel_alert: Original Sentinel alert data
            
        Returns:
            List of warnings from finalization
        """
        warnings: List[str] = []
        
        try:
            # Ensure required fields are present
            if not hit.howler or not hit.howler.id:
                if not hit.howler:
                    hit.howler = HowlerData()
                hit.howler.id = f"sentinel_{uuid.uuid4()}"
                warnings.append("Missing howler ID, generated fallback")
            
            # Set timestamp if missing
            try:
                if not hasattr(hit, 'timestamp') or not hit.timestamp:
                    hit.timestamp = datetime.utcnow().isoformat() + 'Z'
                    warnings.append("Missing timestamp, using current time")
            except Exception as e:
                warnings.append(f"Failed to set timestamp: {str(e)}")
            
            # Add metadata about the mapping process
            try:
                if not hasattr(hit.howler, 'data') or not hit.howler.data:
                    hit.howler.data = {}
                hit.howler.data['mapped_at'] = datetime.utcnow().isoformat() + 'Z'
                hit.howler.data['mapper_version'] = '1.0.0'
            except Exception as e:
                warnings.append(f"Failed to add mapping metadata: {str(e)}")
            
            # Sort and deduplicate tags
            try:
                if hit.tags:
                    hit.tags = sorted(list(set(hit.tags)))
            except Exception as e:
                warnings.append(f"Failed to process tags: {str(e)}")
                
        except Exception as e:
            warnings.append(f"Critical error during hit finalization: {str(e)}")
            
        return warnings
    
    def _safe_parse_datetime(self, date_str: Optional[str]) -> Optional[str]:
        """
        Safely parse datetime string with error handling.
        
        Args:
            date_str: ISO datetime string
            
        Returns:
            Validated datetime string or None if invalid
        """
        if not date_str or not isinstance(date_str, str):
            return None
        
        try:
            # Validate the datetime format
            datetime.fromisoformat(date_str.replace('Z', '+00:00'))
            return date_str
        except (ValueError, AttributeError) as e:
            self.logger.debug("Invalid datetime format: %s - %s", date_str, str(e))
            return None
    
    def _finalize_process_mapping(self, hit: Hit) -> None:
        """
        Finalize process mapping by calling the process mapper's finalization method.
        
        This ensures that all process evidence is properly aggregated and
        the complete process hierarchy is built.
        
        Args:
            hit: Hit object to finalize
        """
        # Get the process mapper from registry
        process_mapper = evidence_mapper_registry.get_mapper(
            "#microsoft.graph.security.processEvidence"
        )
        
        if process_mapper and hasattr(process_mapper, 'finalize_process_mapping'):
            process_mapper.finalize_process_mapping(hit)
            self.logger.debug("Finalized process mapping for hit %s", hit.howler.id)
