# Generated by GitHub Copilot – follow project guidelines above
"""
Base mapper class and common utilities for Sentinel to ECS transformation.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional, Type, TypeVar, Union
from datetime import datetime

from howler.common.logging import get_logger
from howler.odm.models.hit import Hit

T = TypeVar('T')

logger = get_logger(__file__)


class MappingError(Exception):
    """Exception raised when mapping fails."""
    pass


class BaseMapper(ABC):
    """
    Base class for mapping Sentinel evidence to ECS fields.
    
    This abstract base class defines the interface for all evidence mappers
    and provides common utility methods for data transformation.
    """
    
    def __init__(self) -> None:
        self.logger = get_logger(self.__class__.__module__)
    
    @abstractmethod
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map evidence data to ECS fields in the hit.
        
        Args:
            evidence: The evidence data from Sentinel alert
            hit: The hit object to populate with mapped data
            
        Returns:
            Updated hit object with mapped ECS fields
            
        Raises:
            MappingError: If mapping fails due to invalid data
        """
        pass
    
    def safe_get(self, data: Dict[str, Any], key: str, default: Optional[Any] = None) -> Any:
        """
        Safely extract a value from dictionary with logging.
        
        Args:
            data: Source dictionary
            key: Key to extract
            default: Default value if key doesn't exist
            
        Returns:
            Value from dictionary or default
        """
        try:
            return data.get(key, default)
        except (KeyError, AttributeError) as e:
            self.logger.debug("Failed to get key %s from data: %s", key, str(e))
            return default
    
    def safe_get_nested(self, data: Dict[str, Any], path: str, default: Optional[Any] = None) -> Any:
        """
        Safely extract a nested value using dot notation.
        
        Args:
            data: Source dictionary
            path: Dot-separated path to value (e.g., 'userAccount.accountName')
            default: Default value if path doesn't exist
            
        Returns:
            Value from nested path or default
        """
        try:
            keys = path.split('.')
            current = data
            for key in keys:
                if isinstance(current, dict) and key in current:
                    current = current[key]
                else:
                    return default
            return current
        except (AttributeError, TypeError) as e:
            self.logger.debug("Failed to get nested path %s from data: %s", path, str(e))
            return default
    
    def parse_datetime(self, date_str: Optional[str]) -> Optional[str]:
        """
        Parse and validate datetime string.
        
        Args:
            date_str: ISO datetime string from Sentinel
            
        Returns:
            Validated datetime string or None if invalid
        """
        if not date_str:
            return None
        
        try:
            # Validate the datetime format
            datetime.fromisoformat(date_str.replace('Z', '+00:00'))
            return date_str
        except (ValueError, AttributeError) as e:
            self.logger.warning("Invalid datetime format: %s - %s", date_str, str(e))
            return None
    
    def aggregate_list_field(self, existing: Optional[List[str]], new_value: Optional[str]) -> List[str]:
        """
        Aggregate values into a list, avoiding duplicates.
        
        Args:
            existing: Existing list values
            new_value: New value to add
            
        Returns:
            Updated list with new value if not already present
        """
        result = existing or []
        if new_value and new_value not in result:
            result.append(new_value)
        return result
    
    def merge_dict_field(self, existing: Optional[Dict[str, Any]], new_data: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Merge dictionary fields, preferring non-None values.
        
        Args:
            existing: Existing dictionary
            new_data: New dictionary to merge
            
        Returns:
            Merged dictionary
        """
        result = existing or {}
        if new_data:
            for key, value in new_data.items():
                if value is not None:
                    result[key] = value
        return result


class EvidenceMapperRegistry:
    """
    Registry for managing evidence mappers based on @odata.type.
    """
    
    def __init__(self) -> None:
        self._mappers: Dict[str, BaseMapper] = {}
    
    def register(self, odata_type: str, mapper: BaseMapper) -> None:
        """
        Register a mapper for a specific @odata.type.
        
        Args:
            odata_type: The @odata.type identifier
            mapper: The mapper instance
        """
        self._mappers[odata_type] = mapper
        logger.debug("Registered mapper for %s", odata_type)
    
    def get_mapper(self, odata_type: str) -> Optional[BaseMapper]:
        """
        Get mapper for a specific @odata.type.
        
        Args:
            odata_type: The @odata.type identifier
            
        Returns:
            Mapper instance or None if not registered
        """
        return self._mappers.get(odata_type)
    
    def get_supported_types(self) -> List[str]:
        """
        Get list of supported @odata.type values.
        
        Returns:
            List of supported evidence types
        """
        return list(self._mappers.keys())


# Global registry instance
evidence_mapper_registry = EvidenceMapperRegistry()
