# Generated by GitHub Copilot – follow project guidelines above
"""
Cloud application evidence mapper for transforming Sentinel cloud app evidence to ECS cloud fields.
"""

from typing import Any, Dict, Optional

from howler.common.exceptions import HowlerKeyError
from howler.odm.models.hit import Hit
from howler.odm.models.ecs.cloud import Cloud

from .base import BaseMapper, MappingError


class CloudApplicationEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel cloud application evidence to ECS cloud fields.
    
    Cloud application evidence contains information about cloud applications
    involved in alerts, including app IDs and display names.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map cloud application evidence to ECS cloud fields.
        
        Args:
            evidence: Cloud application evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with cloud application information
            
        Raises:
            MappingError: If critical cloud app data is missing or invalid
        """
        try:
            # Extract cloud application information
            app_id = self.safe_get(evidence, 'appId')
            display_name = self.safe_get(evidence, 'displayName')
            
            if not app_id and not display_name:
                raise MappingError("Cloud application evidence missing both appId and displayName")
            
            # Create or update cloud information
            try:
                if not hit.cloud:
                    hit.cloud = Cloud()
            except (AttributeError, HowlerKeyError):
                hit.cloud = Cloud()
            
            # Set cloud application fields
            if app_id:
                # Use project.id for application ID as it's the closest ECS field
                if not hit.cloud.project:
                    hit.cloud.project = {}
                hit.cloud.project['id'] = str(app_id)
            
            if display_name:
                if not hit.cloud.project:
                    hit.cloud.project = {}
                hit.cloud.project['name'] = display_name
            
            # Add cloud application metadata
            self._add_cloud_app_metadata(evidence, hit, app_id, display_name)
            
            self.logger.debug(
                "Successfully mapped cloud application evidence: %s (ID: %s)",
                display_name or "Unknown App", app_id or "Unknown ID"
            )
            
            return hit
            
        except Exception as e:
            if isinstance(e, MappingError):
                raise
            raise MappingError(f"Failed to map cloud application evidence: {str(e)}") from e
    
    def _add_cloud_app_metadata(
        self, 
        evidence: Dict[str, Any], 
        hit: Hit, 
        app_id: Optional[str], 
        display_name: Optional[str]
    ) -> None:
        """
        Add cloud application-specific metadata to the hit.
        
        Args:
            evidence: Original cloud application evidence data
            hit: Hit object to update
            app_id: Application ID
            display_name: Application display name
        """
        # Add cloud application tags
        if not hit.tags:
            hit.tags = []
        
        # Tag for cloud application activity
        if "cloud:application" not in hit.tags:
            hit.tags.append("cloud:application")
        
        # Add verdict-based tags
        verdict = self.safe_get(evidence, 'verdict')
        if verdict:
            verdict_tag = f"cloud:verdict:{verdict}"
            if verdict_tag not in hit.tags:
                hit.tags.append(verdict_tag)
        
        # Store raw evidence data for analysis
        if not hasattr(hit, '_evidence_metadata'):
            hit._evidence_metadata = {}
        
        hit._evidence_metadata['cloud_application_evidence'] = {
            'app_id': app_id,
            'display_name': display_name,
            'verdict': verdict,
            'remediation_status': self.safe_get(evidence, 'remediationStatus'),
            'roles': self.safe_get(evidence, 'roles', []),
            'tags': self.safe_get(evidence, 'tags', [])
        }


class OAuthApplicationEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel OAuth application evidence to ECS cloud fields.
    
    OAuth application evidence contains information about OAuth applications
    involved in alerts, including app IDs, object IDs, and publisher information.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map OAuth application evidence to ECS cloud fields.
        
        Args:
            evidence: OAuth application evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with OAuth application information
            
        Raises:
            MappingError: If critical OAuth app data is missing or invalid
        """
        try:
            # Extract OAuth application information
            app_id = self.safe_get(evidence, 'appId')
            object_id = self.safe_get(evidence, 'objectId')
            display_name = self.safe_get(evidence, 'displayName')
            publisher = self.safe_get(evidence, 'publisher')
            
            if not app_id and not object_id and not display_name:
                raise MappingError("OAuth application evidence missing identifying information")
            
            # Create or update cloud information
            try:
                if not hit.cloud:
                    hit.cloud = Cloud()
            except (AttributeError, HowlerKeyError):
                hit.cloud = Cloud()
            
            # Set OAuth application fields
            if app_id:
                if not hit.cloud.project:
                    hit.cloud.project = {}
                hit.cloud.project['id'] = str(app_id)
            
            if display_name:
                if not hit.cloud.project:
                    hit.cloud.project = {}
                hit.cloud.project['name'] = display_name
            
            # Add OAuth application metadata
            self._add_oauth_app_metadata(evidence, hit, app_id, object_id, display_name, publisher)
            
            self.logger.debug(
                "Successfully mapped OAuth application evidence: %s (App ID: %s, Publisher: %s)",
                display_name or "Unknown App", app_id or "Unknown ID", publisher or "Unknown"
            )
            
            return hit
            
        except Exception as e:
            if isinstance(e, MappingError):
                raise
            raise MappingError(f"Failed to map OAuth application evidence: {str(e)}") from e
    
    def _add_oauth_app_metadata(
        self, 
        evidence: Dict[str, Any], 
        hit: Hit, 
        app_id: Optional[str], 
        object_id: Optional[str],
        display_name: Optional[str],
        publisher: Optional[str]
    ) -> None:
        """
        Add OAuth application-specific metadata to the hit.
        
        Args:
            evidence: Original OAuth application evidence data
            hit: Hit object to update
            app_id: Application ID
            object_id: Object ID
            display_name: Application display name
            publisher: Application publisher
        """
        # Add OAuth application tags
        if not hit.tags:
            hit.tags = []
        
        # Tag for OAuth application activity
        if "oauth:application" not in hit.tags:
            hit.tags.append("oauth:application")
        
        # Add verdict-based tags
        verdict = self.safe_get(evidence, 'verdict')
        if verdict:
            verdict_tag = f"oauth:verdict:{verdict}"
            if verdict_tag not in hit.tags:
                hit.tags.append(verdict_tag)
        
        # Store raw evidence data for analysis
        if not hasattr(hit, '_evidence_metadata'):
            hit._evidence_metadata = {}
        
        hit._evidence_metadata['oauth_application_evidence'] = {
            'app_id': app_id,
            'object_id': object_id,
            'display_name': display_name,
            'publisher': publisher,
            'verdict': verdict,
            'remediation_status': self.safe_get(evidence, 'remediationStatus'),
            'roles': self.safe_get(evidence, 'roles', []),
            'tags': self.safe_get(evidence, 'tags', [])
        }
