# Generated by GitHub Copilot – follow project guidelines above
"""
Device evidence mapper for transforming Sentinel device evidence to ECS host fields.
"""

from typing import Any, Dict, List, Optional

from howler.common.exceptions import HowlerKeyError
from howler.odm.models.hit import Hit
from howler.odm.models.ecs.host import Host

from .base import BaseMapper, MappingError


class DeviceEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel device evidence to ECS host fields.
    
    Device evidence contains information about the host/device where the alert occurred,
    including device metadata, IP addresses, and logged-on users.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map device evidence to ECS host fields.
        
        Args:
            evidence: Device evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with host information
            
        Raises:
            MappingError: If critical device data is missing or invalid
        """
        try:
            # Extract device information
            device_dns_name = self.safe_get(evidence, 'deviceDnsName')
            host_name = self.safe_get(evidence, 'hostName')
            mde_device_id = self.safe_get(evidence, 'mdeDeviceId')
            
            # Use the most appropriate name available
            host_display_name = device_dns_name or host_name
            
            if not host_display_name and not mde_device_id:
                raise MappingError("Device evidence missing both host name and device ID")
            
            # Create or update host information
            try:
                if not hit.host:
                    hit.host = Host()
            except (AttributeError, HowlerKeyError):
                hit.host = Host()
            
            # Map host identification
            if mde_device_id:
                hit.host.id = mde_device_id
            
            if host_display_name:
                hit.host.name = host_display_name
            
            # Map domain information
            nt_domain = self.safe_get(evidence, 'ntDomain')
            dns_domain = self.safe_get(evidence, 'dnsDomain')
            domain = nt_domain or dns_domain
            if domain:
                try:
                    hit.host.domain = domain
                except (AttributeError, HowlerKeyError):
                    # If we can't assign to host.domain, skip domain mapping
                    pass
            
            # Map IP addresses
            ip_addresses = self._extract_ip_addresses(evidence)
            if ip_addresses:
                # Merge with existing IPs, avoiding duplicates
                try:
                    existing_ips = hit.host.ip or []
                except (AttributeError, HowlerKeyError):
                    existing_ips = []
                for ip in ip_addresses:
                    if ip not in existing_ips:
                        existing_ips.append(ip)
                try:
                    hit.host.ip = existing_ips
                except (AttributeError, HowlerKeyError):
                    # If we can't assign to host.ip, the host object may not be properly initialized
                    pass
            
            # Map platform information to host type
            os_platform = self.safe_get(evidence, 'osPlatform')
            if os_platform:
                try:
                    hit.host.type = os_platform.lower()
                except (AttributeError, HowlerKeyError):
                    # If we can't assign to host.type, skip platform mapping
                    pass
            
            # Log successful mapping
            self.logger.debug(
                "Mapped device evidence: host_name=%s, device_id=%s, ip_count=%d",
                host_display_name,
                mde_device_id,
                len(ip_addresses)
            )
            
            return hit
            
        except Exception as e:
            self.logger.error("Failed to map device evidence: %s", str(e))
            raise MappingError(f"Device evidence mapping failed: {str(e)}") from e
    
    def _extract_ip_addresses(self, evidence: Dict[str, Any]) -> List[str]:
        """
        Extract and validate IP addresses from device evidence.
        
        Args:
            evidence: Device evidence data
            
        Returns:
            List of valid IP addresses
        """
        ip_addresses = []
        
        # Get primary IP addresses
        last_ip = self.safe_get(evidence, 'lastIpAddress')
        if last_ip and self._is_valid_ip(last_ip):
            ip_addresses.append(last_ip)
        
        last_external_ip = self.safe_get(evidence, 'lastExternalIpAddress')
        if last_external_ip and self._is_valid_ip(last_external_ip):
            ip_addresses.append(last_external_ip)
        
        # Get interface IP addresses
        ip_interfaces = self.safe_get(evidence, 'ipInterfaces', [])
        if isinstance(ip_interfaces, list):
            for ip in ip_interfaces:
                if isinstance(ip, str) and self._is_valid_ip(ip) and ip not in ip_addresses:
                    ip_addresses.append(ip)
        
        return ip_addresses
    
    def _is_valid_ip(self, ip_str: str) -> bool:
        """
        Validate IP address format.
        
        Args:
            ip_str: IP address string to validate
            
        Returns:
            True if valid IP address format
        """
        try:
            import ipaddress
            ipaddress.ip_address(ip_str)
            return True
        except (ValueError, AttributeError):
            self.logger.debug("Invalid IP address format: %s", ip_str)
            return False
