# Generated by GitHub Copilot – follow project guidelines above
"""
File evidence mapper for transforming Sentinel file evidence to ECS file fields.
"""

from typing import Any, Dict, List, Optional

from howler.common.exceptions import HowlerKeyError
from howler.odm.models.hit import Hit
from howler.odm.models.ecs.file import File
from howler.odm.models.ecs.hash import Hashes

from .base import BaseMapper, MappingError


class FileEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel file evidence to ECS file fields.
    
    File evidence contains information about files involved in the alert,
    including file paths, hashes, sizes, and metadata.
    
    Note: Since ECS supports a single file field but Sentinel can have multiple
    file evidence items, this mapper implements a "primary file" strategy where
    the most significant file becomes the main file field and others are stored
    in related fields or tags.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map file evidence to ECS file fields.
        
        Args:
            evidence: File evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with file information
            
        Raises:
            MappingError: If critical file data is missing or invalid
        """
        try:
            # Extract file details
            file_details = self.safe_get(evidence, 'fileDetails')
            if not file_details:
                raise MappingError("File evidence missing fileDetails")
            
            file_name = self.safe_get(file_details, 'fileName')
            file_path = self.safe_get(file_details, 'filePath')
            
            if not file_name and not file_path:
                raise MappingError("File evidence missing both fileName and filePath")
            
            # Determine if this should be the primary file or additional context
            try:
                if not hit.file:
                    hit.file = self._create_primary_file(file_details)
                    self.logger.debug("Created primary file: %s", file_name or file_path)
                else:
                    # This is additional file context
                    self._add_file_context(file_details, hit)
                    self.logger.debug("Added file context: %s", file_name or file_path)
            except (AttributeError, HowlerKeyError):
                hit.file = self._create_primary_file(file_details)
                self.logger.debug("Created primary file: %s", file_name or file_path)
            
            return hit
            
        except Exception as e:
            self.logger.error("Failed to map file evidence: %s", str(e))
            raise MappingError(f"File evidence mapping failed: {str(e)}") from e
    
    def _create_primary_file(self, file_details: Dict[str, Any]) -> File:
        """
        Create primary file from file details.
        
        Args:
            file_details: File details from evidence
            
        Returns:
            Populated File object
        """
        file_obj = File()
        
        # Basic file information
        file_name = self.safe_get(file_details, 'fileName')
        if file_name:
            file_obj.name = file_name
            file_obj.extension = self._extract_file_extension(file_name)
        
        file_path = self.safe_get(file_details, 'filePath')
        if file_path:
            file_obj.directory = file_path
            # Build full path if both path and name are available
            if file_name:
                file_obj.path = self._build_full_path(file_path, file_name)
        
        # File size
        file_size = self.safe_get(file_details, 'fileSize')
        if file_size is not None:
            try:
                file_obj.size = int(file_size)
            except (ValueError, TypeError):
                self.logger.debug("Invalid file size: %s", file_size)
        
        # File hashes
        file_obj.hash = self._extract_file_hashes(file_details)
        
        # Publisher/signer information (if available)
        file_publisher = self.safe_get(file_details, 'filePublisher')
        signer = self.safe_get(file_details, 'signer')
        issuer = self.safe_get(file_details, 'issuer')
        
        # Note: ECS file doesn't have direct publisher/signer fields
        # These could be stored in code_signature if available
        if signer or issuer:
            # This would require creating a CodeSignature object
            # For now, we'll log this information
            self.logger.debug(
                "File signing info - publisher: %s, signer: %s, issuer: %s",
                file_publisher,
                signer,
                issuer
            )
        
        return file_obj
    
    def _add_file_context(self, file_details: Dict[str, Any], hit: Hit) -> None:
        """
        Add additional file context to the hit.
        
        Since ECS has a single file field, additional files are added to tags
        or related fields for context.
        
        Args:
            file_details: Additional file details
            hit: Hit object with existing file data
        """
        file_name = self.safe_get(file_details, 'fileName')
        file_path = self.safe_get(file_details, 'filePath')
        
        # Add file name to tags for searchability
        if file_name:
            file_tag = f"file:{file_name}"
            hit.tags = self.aggregate_list_field(hit.tags, file_tag)
        
        # Add file path to tags
        if file_path:
            path_tag = f"path:{file_path}"
            hit.tags = self.aggregate_list_field(hit.tags, path_tag)
        
        # If the existing file doesn't have hashes but this one does, consider updating
        file_hashes = self._extract_file_hashes(file_details)
        if file_hashes and not hit.file.hash:
            hit.file.hash = file_hashes
            self.logger.debug("Updated primary file with hashes from additional evidence")
    
    def _extract_file_extension(self, file_name: str) -> Optional[str]:
        """
        Extract file extension from filename.
        
        Args:
            file_name: Name of the file
            
        Returns:
            File extension without the dot, or None
        """
        if not file_name or '.' not in file_name:
            return None
        
        extension = file_name.split('.')[-1].lower()
        return extension if extension != file_name.lower() else None
    
    def _build_full_path(self, file_path: str, file_name: str) -> str:
        """
        Build full file path from directory and filename.
        
        Args:
            file_path: Directory path
            file_name: File name
            
        Returns:
            Complete file path
        """
        # Determine path separator
        separator = '/' if '/' in file_path else '\\'
        
        # Ensure path ends with separator
        if not file_path.endswith(separator):
            file_path += separator
        
        return file_path + file_name
    
    def _extract_file_hashes(self, file_details: Dict[str, Any]) -> Optional[Hashes]:
        """
        Extract file hashes from file details.
        
        Args:
            file_details: File details containing hash information
            
        Returns:
            Hashes object or None if no hashes available
        """
        sha1 = self.safe_get(file_details, 'sha1')
        sha256 = self.safe_get(file_details, 'sha256')
        md5 = self.safe_get(file_details, 'md5')
        sha256_ac = self.safe_get(file_details, 'sha256Ac')  # Authenticode hash
        
        if sha1 or sha256 or md5 or sha256_ac:
            hashes = Hashes()
            
            if sha1:
                hashes.sha1 = sha1
            if sha256:
                hashes.sha256 = sha256
            if md5:
                hashes.md5 = md5
            # Note: sha256Ac (Authenticode) might need special handling
            # depending on how ECS Hashes model is structured
            
            return hashes
        
        return None
    
    def _determine_file_significance(self, file_details: Dict[str, Any]) -> int:
        """
        Determine the significance of a file for prioritization.
        
        This helps decide which file should be the primary file when multiple
        file evidence items exist.
        
        Args:
            file_details: File details to evaluate
            
        Returns:
            Significance score (higher = more significant)
        """
        score = 0
        
        # Files with hashes are more significant
        if (self.safe_get(file_details, 'sha1') or 
            self.safe_get(file_details, 'sha256') or 
            self.safe_get(file_details, 'md5')):
            score += 10
        
        # Files with size information are more significant
        if self.safe_get(file_details, 'fileSize'):
            score += 5
        
        # Executable files are more significant
        file_name = self.safe_get(file_details, 'fileName', '')
        if file_name.lower().endswith(('.exe', '.dll', '.bin', '.so')):
            score += 15
        
        # Files with signing information are more significant
        if (self.safe_get(file_details, 'signer') or 
            self.safe_get(file_details, 'issuer')):
            score += 8
        
        return score
