# Generated by GitHub Copilot – follow project guidelines above
"""
IP evidence mapper for transforming Sentinel IP evidence to ECS network fields.
"""

from typing import Any, Dict, Optional

from howler.common.exceptions import HowlerKeyError
from howler.odm.models.hit import Hit
from howler.odm.models.ecs.host import Host
from howler.odm.models.ecs.network import Network
from howler.odm.models.ecs.geo import Geo

from .base import BaseMapper, MappingError


class IpEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel IP evidence to ECS network and host fields.
    
    IP evidence contains information about IP addresses involved in alerts,
    including geolocation data and network context.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map IP evidence to ECS network and host fields.
        
        Args:
            evidence: IP evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with IP and network information
            
        Raises:
            MappingError: If critical IP data is missing or invalid
        """
        try:
            # Extract IP address information
            ip_address = self.safe_get(evidence, 'ipAddress')
            country_code = self.safe_get(evidence, 'countryCode')
            
            if not ip_address:
                raise MappingError("IP evidence missing required ipAddress field")
            
            # Validate IP address format
            try:
                import ipaddress
                ip_obj = ipaddress.ip_address(ip_address)
                is_private = ip_obj.is_private
            except ValueError as e:
                raise MappingError(f"Invalid IP address format: {ip_address}") from e
            
            # Create or update host information for IP
            try:
                if not hit.host:
                    hit.host = Host()
            except (AttributeError, HowlerKeyError):
                hit.host = Host()
            
            # Add IP to host.ip list if not already present
            try:
                if not hit.host.ip:
                    hit.host.ip = []
            except (AttributeError, HowlerKeyError):
                hit.host.ip = []
            
            try:
                if ip_address not in hit.host.ip:
                    hit.host.ip.append(ip_address)
            except (AttributeError, HowlerKeyError):
                # If we can't access or modify hit.host.ip, create a new list
                hit.host.ip = [ip_address]
            
            # Add geolocation information if available
            if country_code:
                try:
                    if not hit.host.geo:
                        hit.host.geo = Geo()
                except (AttributeError, HowlerKeyError):
                    hit.host.geo = Geo()
                try:
                    hit.host.geo.country_iso_code = country_code
                except (AttributeError, HowlerKeyError):
                    # If we can't assign to geo.country_iso_code, skip geo mapping
                    pass
            
            # Create or update network information
            try:
                if not hit.network:
                    hit.network = Network()
            except (AttributeError, HowlerKeyError):
                hit.network = Network()
            
            # Set network type based on IP characteristics
            try:
                if is_private:
                    hit.network.type = "private"
                else:
                    hit.network.type = "public"
            except (AttributeError, HowlerKeyError):
                # If we can't assign to network.type, skip network type mapping
                pass
            
            # Add IP classification metadata
            self._add_ip_metadata(evidence, hit, ip_address, is_private)
            
            self.logger.debug(
                "Successfully mapped IP evidence: %s (country: %s, private: %s)",
                ip_address, country_code or "unknown", is_private
            )
            
            return hit
            
        except Exception as e:
            if isinstance(e, MappingError):
                raise
            raise MappingError(f"Failed to map IP evidence: {str(e)}") from e
    
    def _add_ip_metadata(
        self, 
        evidence: Dict[str, Any], 
        hit: Hit, 
        ip_address: str, 
        is_private: bool
    ) -> None:
        """
        Add IP-specific metadata to the hit.
        
        Args:
            evidence: Original IP evidence data
            hit: Hit object to update
            ip_address: Extracted IP address
            is_private: Whether the IP is in private address space
        """
        # Add IP classification tags
        if not hit.tags:
            hit.tags = []
        
        # Tag based on IP type
        ip_type_tag = f"ip:{'private' if is_private else 'public'}"
        if ip_type_tag not in hit.tags:
            hit.tags.append(ip_type_tag)
        
        # Add evidence-specific tags
        verdict = self.safe_get(evidence, 'verdict')
        if verdict:
            verdict_tag = f"ip:verdict:{verdict}"
            if verdict_tag not in hit.tags:
                hit.tags.append(verdict_tag)
        
        # Store raw evidence data for analysis
        if not hasattr(hit, '_evidence_metadata'):
            hit._evidence_metadata = {}
        
        hit._evidence_metadata['ip_evidence'] = {
            'address': ip_address,
            'is_private': is_private,
            'verdict': verdict,
            'remediation_status': self.safe_get(evidence, 'remediationStatus'),
            'roles': self.safe_get(evidence, 'roles', []),
            'tags': self.safe_get(evidence, 'tags', [])
        }
