# Generated by GitHub Copilot – follow project guidelines above
"""
Process evidence mapper for transforming Sentinel process evidence to ECS process fields.
"""

from typing import Any, Dict, List, Optional

from howler.common.exceptions import HowlerKeyError
from howler.odm.models.hit import Hit
from howler.odm.models.ecs.process import Process, ParentProcess, ParentParentProcess
from howler.odm.models.ecs.file import File
from howler.odm.models.ecs.hash import Hashes
from howler.odm.models.ecs.user import ShortUser

from .base import BaseMapper, MappingError


class ProcessEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel process evidence to ECS process fields.
    
    Process evidence contains information about processes involved in the alert,
    including command lines, PIDs, file hashes, and user context.
    
    This mapper implements intelligent process hierarchy reconstruction by:
    1. Collecting all process evidence items first
    2. Building a process tree based on parent-child relationships
    3. Mapping the tree to ECS process hierarchy (process -> parent -> parent.parent)
    """
    
    def __init__(self) -> None:
        super().__init__()
        self._process_evidence_cache: List[Dict[str, Any]] = []
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map process evidence to ECS process fields.
        
        This method accumulates process evidence and builds the hierarchy
        when the first process is encountered or when explicitly finalized.
        
        Args:
            evidence: Process evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with process information
            
        Raises:
            MappingError: If critical process data is missing or invalid
        """
        try:
            # Cache this evidence for hierarchy building
            self._process_evidence_cache.append(evidence)
            
            # If this is the first process evidence, start building the hierarchy
            try:
                if not hit.process:
                    hit.process = self._build_process_hierarchy()
                    self.logger.debug(
                        "Built process hierarchy with %d evidence items", 
                        len(self._process_evidence_cache)
                    )
            except (AttributeError, HowlerKeyError):
                hit.process = self._build_process_hierarchy()
                self.logger.debug(
                    "Built process hierarchy with %d evidence items", 
                    len(self._process_evidence_cache)
                )
            
            return hit
            
        except Exception as e:
            self.logger.error("Failed to map process evidence: %s", str(e))
            raise MappingError(f"Process evidence mapping failed: {str(e)}") from e
    
    def finalize_process_mapping(self, hit: Hit) -> Hit:
        """
        Finalize process mapping by building complete hierarchy from cached evidence.
        
        Args:
            hit: Hit object to finalize
            
        Returns:
            Hit with complete process hierarchy
        """
        if self._process_evidence_cache and not hit.process:
            hit.process = self._build_process_hierarchy()
        
        # Clear cache after processing
        self._process_evidence_cache.clear()
        return hit
    
    def _build_process_hierarchy(self) -> Optional[Process]:
        """
        Build complete process hierarchy from cached evidence items.
        
        Returns:
            Complete Process object with parent hierarchy
        """
        if not self._process_evidence_cache:
            return None
        
        # Group evidence by process ID for easier lookup
        processes_by_id = {}
        for evidence in self._process_evidence_cache:
            process_id = evidence.get('processId')
            if process_id is not None:
                processes_by_id[process_id] = evidence
        
        # Find the primary process (most recent or with most complete data)
        primary_evidence = self._identify_primary_process()
        if not primary_evidence:
            self.logger.warning("No suitable primary process found in evidence")
            return None
        
        # Build the main process
        process = self._create_process_from_evidence(primary_evidence)
        
        # Build parent hierarchy
        process.parent = self._build_parent_process(primary_evidence, processes_by_id)
        
        return process
    
    def _identify_primary_process(self) -> Optional[Dict[str, Any]]:
        """
        Identify the primary process from available evidence.
        
        Priority order:
        1. Process with command line and complete data
        2. Most recent process
        3. First process in the list
        
        Returns:
            Primary process evidence or None
        """
        if not self._process_evidence_cache:
            return None
        
        # Score processes based on completeness
        scored_processes = []
        for evidence in self._process_evidence_cache:
            score = 0
            if evidence.get('processCommandLine'):
                score += 10
            if evidence.get('imageFile'):
                score += 5
            if evidence.get('processCreationDateTime'):
                score += 3
            if evidence.get('userAccount'):
                score += 2
            
            scored_processes.append((score, evidence))
        
        # Return highest scoring process
        scored_processes.sort(key=lambda x: x[0], reverse=True)
        return scored_processes[0][1] if scored_processes else None
    
    def _create_process_from_evidence(self, evidence: Dict[str, Any]) -> Process:
        """
        Create a complete Process object from evidence data.
        
        Args:
            evidence: Process evidence data
            
        Returns:
            Populated Process object
        """
        process = Process()
        
        # Basic process information
        process_id = self.safe_get(evidence, 'processId')
        if process_id is not None:
            process.pid = int(process_id)
        
        parent_process_id = self.safe_get(evidence, 'parentProcessId')
        if parent_process_id is not None:
            process.ppid = int(parent_process_id)
        
        command_line = self.safe_get(evidence, 'processCommandLine')
        if command_line:
            process.command_line = command_line
            # Extract process name and arguments
            process.name = self._extract_process_name(command_line)
            process.args = self._extract_process_args(command_line)
            if process.args:
                process.args_count = len(process.args)
        
        # Process timing
        creation_time = self.safe_get(evidence, 'processCreationDateTime')
        if creation_time:
            process.start = self.parse_datetime(creation_time)
        
        # Map executable file information
        image_file = self.safe_get(evidence, 'imageFile')
        if image_file:
            process.executable = self._build_executable_path(image_file)
            process.hash = self._extract_file_hashes(image_file)
        
        # Map user account information
        user_account = self.safe_get(evidence, 'userAccount')
        if user_account:
            process.user = self._map_user_account(user_account)
        
        return process
    
    def _build_parent_process(self, primary_evidence: Dict[str, Any], 
                            processes_by_id: Dict[int, Dict[str, Any]]) -> Optional[ParentProcess]:
        """
        Build parent process from evidence data.
        
        Args:
            primary_evidence: Primary process evidence
            processes_by_id: Lookup table of process evidence by ID
            
        Returns:
            ParentProcess object or None
        """
        parent_id = primary_evidence.get('parentProcessId')
        if parent_id is None:
            return None
        
        # Look for parent process evidence
        parent_evidence = processes_by_id.get(parent_id)
        if not parent_evidence:
            # Create minimal parent from available data
            parent_evidence = primary_evidence
        
        parent = ParentProcess()
        
        # Basic parent information
        if parent_id is not None:
            parent.pid = int(parent_id)
        
        # If we have separate parent evidence, use it
        if parent_evidence != primary_evidence:
            command_line = self.safe_get(parent_evidence, 'processCommandLine')
            if command_line:
                parent.command_line = command_line
                parent.name = self._extract_process_name(command_line)
            
            creation_time = self.safe_get(parent_evidence, 'processCreationDateTime')
            if creation_time:
                parent.start = self.parse_datetime(creation_time)
            
            image_file = self.safe_get(parent_evidence, 'imageFile')
            if image_file:
                parent.executable = self._build_executable_path(image_file)
                parent.hash = self._extract_file_hashes(image_file)
            
            user_account = self.safe_get(parent_evidence, 'userAccount')
            if user_account:
                parent.user = self._map_user_account(user_account)
        else:
            # Use parent creation time from primary evidence
            parent_creation_time = self.safe_get(primary_evidence, 'parentProcessCreationDateTime')
            if parent_creation_time:
                parent.start = self.parse_datetime(parent_creation_time)
        
        # Try to build grandparent if we have the data
        grandparent_id = parent_evidence.get('parentProcessId')
        if grandparent_id and grandparent_id != parent_id and grandparent_id in processes_by_id:
            parent.parent = self._build_grandparent_process(
                processes_by_id[grandparent_id]
            )
        
        return parent
    
    def _build_grandparent_process(self, grandparent_evidence: Dict[str, Any]) -> Optional[ParentParentProcess]:
        """
        Build grandparent process (process.parent.parent).
        
        Args:
            grandparent_evidence: Evidence for grandparent process
            
        Returns:
            ParentParentProcess object or None
        """
        grandparent = ParentParentProcess()
        
        process_id = self.safe_get(grandparent_evidence, 'processId')
        if process_id is not None:
            grandparent.pid = int(process_id)
        
        command_line = self.safe_get(grandparent_evidence, 'processCommandLine')
        if command_line:
            grandparent.command_line = command_line
            grandparent.name = self._extract_process_name(command_line)
        
        creation_time = self.safe_get(grandparent_evidence, 'processCreationDateTime')
        if creation_time:
            grandparent.start = self.parse_datetime(creation_time)
        
        image_file = self.safe_get(grandparent_evidence, 'imageFile')
        if image_file:
            grandparent.executable = self._build_executable_path(image_file)
            grandparent.hash = self._extract_file_hashes(image_file)
        
        user_account = self.safe_get(grandparent_evidence, 'userAccount')
        if user_account:
            grandparent.user = self._map_user_account(user_account)
        
        return grandparent
    
    def _extract_process_name(self, command_line: str) -> Optional[str]:
        """
        Extract process name from command line.
        
        Args:
            command_line: Full command line string
            
        Returns:
            Process name or None
        """
        if not command_line:
            return None
        
        # Split command line and get first part (executable)
        parts = command_line.strip().split()
        if parts:
            executable = parts[0]
            # Extract just the filename from path
            if '/' in executable:
                return executable.split('/')[-1]
            elif '\\' in executable:
                return executable.split('\\')[-1]
            return executable
        
        return None
    
    def _extract_process_args(self, command_line: str) -> Optional[List[str]]:
        """
        Extract process arguments from command line.
        
        Args:
            command_line: Full command line string
            
        Returns:
            List of arguments including executable path, or None
        """
        if not command_line:
            return None
        
        # Simple splitting - could be enhanced with proper shell parsing
        args = command_line.strip().split()
        return args if args else None
    
    def _build_executable_path(self, image_file: Dict[str, Any]) -> Optional[str]:
        """
        Build full executable path from image file data.
        
        Args:
            image_file: Image file information
            
        Returns:
            Full executable path or None
        """
        file_path = self.safe_get(image_file, 'filePath')
        file_name = self.safe_get(image_file, 'fileName')
        
        if file_path and file_name:
            # Ensure path ends with separator
            separator = '/' if '/' in file_path else '\\'
            if not file_path.endswith(separator):
                file_path += separator
            return file_path + file_name
        elif file_name:
            return file_name
        
        return None
    
    def _extract_file_hashes(self, image_file: Dict[str, Any]) -> Optional[Hashes]:
        """
        Extract file hashes from image file data.
        
        Args:
            image_file: Image file information
            
        Returns:
            Hashes object or None
        """
        sha1 = self.safe_get(image_file, 'sha1')
        sha256 = self.safe_get(image_file, 'sha256')
        md5 = self.safe_get(image_file, 'md5')
        
        if sha1 or sha256 or md5:
            hashes = Hashes()
            if sha1:
                hashes.sha1 = sha1
            if sha256:
                hashes.sha256 = sha256
            if md5:
                hashes.md5 = md5
            return hashes
        
        return None
    
    def _map_user_account(self, user_account: Dict[str, Any]) -> Optional[ShortUser]:
        """
        Map user account information to ECS user format.
        
        Args:
            user_account: User account data from evidence
            
        Returns:
            ShortUser object or None
        """
        account_name = self.safe_get(user_account, 'accountName')
        domain_name = self.safe_get(user_account, 'domainName')
        
        if account_name:
            user = ShortUser()
            user.name = account_name
            if domain_name:
                user.domain = domain_name
            return user
        
        return None
