# Generated by GitHub Copilot – follow project guidelines above
"""
Registry evidence mappers for transforming Sentinel registry evidence to ECS registry fields.
"""

from typing import Any, Dict, Optional

from howler.common.exceptions import HowlerKeyError
from howler.odm.models.hit import Hit
from howler.odm.models.ecs.registry import Registry

from .base import BaseMapper, MappingError


class RegistryKeyEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel registry key evidence to ECS registry fields.
    
    Registry key evidence contains information about Windows registry keys
    involved in alerts, including hive and key path information.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map registry key evidence to ECS registry fields.
        
        Args:
            evidence: Registry key evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with registry key information
            
        Raises:
            MappingError: If critical registry data is missing or invalid
        """
        try:
            # Extract registry key information
            registry_key = self.safe_get(evidence, 'registryKey')
            registry_hive = self.safe_get(evidence, 'registryHive')
            
            if not registry_key:
                raise MappingError("Registry key evidence missing required registryKey field")
            
            # Create or update registry information
            try:
                if not hit.registry:
                    hit.registry = Registry()
            except (AttributeError, HowlerKeyError):
                hit.registry = Registry()
            
            # Set registry fields
            hit.registry.key = registry_key
            if registry_hive:
                hit.registry.hive = registry_hive
            
            # Add registry metadata
            self._add_registry_metadata(evidence, hit, registry_key, registry_hive)
            
            self.logger.debug(
                "Successfully mapped registry key evidence: %s\\%s",
                registry_hive or "UNKNOWN_HIVE", registry_key
            )
            
            return hit
            
        except Exception as e:
            if isinstance(e, MappingError):
                raise
            raise MappingError(f"Failed to map registry key evidence: {str(e)}") from e
    
    def _add_registry_metadata(
        self, 
        evidence: Dict[str, Any], 
        hit: Hit, 
        registry_key: str, 
        registry_hive: Optional[str]
    ) -> None:
        """
        Add registry-specific metadata to the hit.
        
        Args:
            evidence: Original registry evidence data
            hit: Hit object to update
            registry_key: Registry key path
            registry_hive: Registry hive name
        """
        # Add registry tags
        if not hit.tags:
            hit.tags = []
        
        # Tag based on hive
        if registry_hive:
            hive_tag = f"registry:hive:{registry_hive.lower()}"
            if hive_tag not in hit.tags:
                hit.tags.append(hive_tag)
        
        # Tag for registry activity
        if "registry:activity" not in hit.tags:
            hit.tags.append("registry:activity")
        
        # Add verdict-based tags
        verdict = self.safe_get(evidence, 'verdict')
        if verdict:
            verdict_tag = f"registry:verdict:{verdict}"
            if verdict_tag not in hit.tags:
                hit.tags.append(verdict_tag)
        
        # Store raw evidence data for analysis
        if not hasattr(hit, '_evidence_metadata'):
            hit._evidence_metadata = {}
        
        hit._evidence_metadata['registry_key_evidence'] = {
            'key': registry_key,
            'hive': registry_hive,
            'verdict': verdict,
            'remediation_status': self.safe_get(evidence, 'remediationStatus'),
            'roles': self.safe_get(evidence, 'roles', []),
            'tags': self.safe_get(evidence, 'tags', [])
        }


class RegistryValueEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel registry value evidence to ECS registry fields.
    
    Registry value evidence contains information about Windows registry values
    involved in alerts, including hive, key, and value information.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map registry value evidence to ECS registry fields.
        
        Args:
            evidence: Registry value evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with registry value information
            
        Raises:
            MappingError: If critical registry data is missing or invalid
        """
        try:
            # Extract registry value information
            registry_key = self.safe_get(evidence, 'registryKey')
            registry_hive = self.safe_get(evidence, 'registryHive')
            registry_value = self.safe_get(evidence, 'registryValue')
            
            if not registry_key:
                raise MappingError("Registry value evidence missing required registryKey field")
            
            # Create or update registry information
            try:
                if not hit.registry:
                    hit.registry = Registry()
            except (AttributeError, HowlerKeyError):
                hit.registry = Registry()
            
            # Set registry fields
            hit.registry.key = registry_key
            if registry_hive:
                hit.registry.hive = registry_hive
            if registry_value is not None:  # Allow empty string values
                hit.registry.value = str(registry_value)
            
            # Add registry metadata
            self._add_registry_value_metadata(evidence, hit, registry_key, registry_hive, registry_value)
            
            self.logger.debug(
                "Successfully mapped registry value evidence: %s\\%s = %s",
                registry_hive or "UNKNOWN_HIVE", registry_key, 
                str(registry_value)[:50] if registry_value is not None else "None"
            )
            
            return hit
            
        except Exception as e:
            if isinstance(e, MappingError):
                raise
            raise MappingError(f"Failed to map registry value evidence: {str(e)}") from e
    
    def _add_registry_value_metadata(
        self, 
        evidence: Dict[str, Any], 
        hit: Hit, 
        registry_key: str, 
        registry_hive: Optional[str],
        registry_value: Any
    ) -> None:
        """
        Add registry value-specific metadata to the hit.
        
        Args:
            evidence: Original registry evidence data
            hit: Hit object to update
            registry_key: Registry key path
            registry_hive: Registry hive name
            registry_value: Registry value data
        """
        # Add registry tags
        if not hit.tags:
            hit.tags = []
        
        # Tag based on hive
        if registry_hive:
            hive_tag = f"registry:hive:{registry_hive.lower()}"
            if hive_tag not in hit.tags:
                hit.tags.append(hive_tag)
        
        # Tag for registry value modification
        if "registry:value:modified" not in hit.tags:
            hit.tags.append("registry:value:modified")
        
        # Add verdict-based tags
        verdict = self.safe_get(evidence, 'verdict')
        if verdict:
            verdict_tag = f"registry:verdict:{verdict}"
            if verdict_tag not in hit.tags:
                hit.tags.append(verdict_tag)
        
        # Store raw evidence data for analysis
        if not hasattr(hit, '_evidence_metadata'):
            hit._evidence_metadata = {}
        
        hit._evidence_metadata['registry_value_evidence'] = {
            'key': registry_key,
            'hive': registry_hive,
            'value': registry_value,
            'verdict': verdict,
            'remediation_status': self.safe_get(evidence, 'remediationStatus'),
            'roles': self.safe_get(evidence, 'roles', []),
            'tags': self.safe_get(evidence, 'tags', [])
        }
