# Generated by GitHub Copilot – follow project guidelines above
"""
Simplified alert mapper using unified evidence processing.

This module replaces the complex registry-based alert mapping with a streamlined
approach using the unified evidence mapper.
"""

import uuid
from typing import Any, Dict, List, Optional, Tuple
from datetime import datetime, timezone

from howler.common.logging import get_logger
from howler.odm.models.hit import Hit
from howler.odm.models.howler_data import HowlerData

from .unified import UnifiedEvidenceMapper


class SentinelAlertMapper:
    """
    Simplified alert mapper that uses unified evidence processing.
    
    This replaces the complex registry pattern with a single unified mapper,
    reducing code complexity while maintaining all functionality.
    """
    
    def __init__(self) -> None:
        self.logger = get_logger(self.__class__.__module__)
        self.evidence_mapper = UnifiedEvidenceMapper()
    
    def map_alert(self, alert_data: Dict[str, Any]) -> Tuple[Dict[str, Any], List[str]]:
        """
        Map Sentinel alert to ECS-compliant hit data.
        
        Args:
            alert_data: Raw Sentinel alert data
            
        Returns:
            Tuple of (mapped hit data as dict, list of warnings)
        """
        warnings = []
        
        # Check for empty or minimal alert data and add warnings
        if not alert_data:
            warnings.append("Empty alert data provided - using default values for unknown alert")
        else:
            # Check for missing critical fields
            if not alert_data.get("alertDisplayName") and not alert_data.get("systemAlertId"):
                warnings.append("Alert has unknown or missing display name and system ID")
            
            if not alert_data.get("severity"):
                warnings.append("Alert severity is unknown - using default value")
                
            if not alert_data.get("evidence"):
                warnings.append("No evidence items found in alert - hit will contain minimal data")
        
        try:
            # Create base hit object with required howler fields
            hit = self._create_base_hit(alert_data)
            
            # Map basic alert fields
            hit = self._map_alert_metadata(alert_data, hit)
            
            # Process evidence items
            evidence_list = alert_data.get("evidence", [])
            self.logger.debug("Processing %d evidence items", len(evidence_list))
            
            for evidence in evidence_list:
                hit, evidence_warnings = self.evidence_mapper.map_evidence(evidence, hit)
                warnings.extend(evidence_warnings)
            
            # Finalize process hierarchy if any process evidence was found
            hit = self.evidence_mapper.finalize_process_hierarchy(hit)
            
            # Convert hit to dictionary for return
            hit_dict = self._hit_to_dict(hit)
            
            self.logger.info(
                "Successfully mapped alert %s with %d evidence items",
                alert_data.get("systemAlertId", "unknown"),
                len(evidence_list)
            )
            
            return hit_dict, warnings
            
        except Exception as e:
            error_msg = f"Failed to map alert: {str(e)}"
            self.logger.error(error_msg, exc_info=True)
            warnings.append(error_msg)
            
            # Return minimal hit data on error
            return self._create_minimal_hit(alert_data), warnings
    
    def _create_base_hit(self, alert_data: Dict[str, Any]) -> Hit:
        """
        Create a base Hit object with required howler fields.
        
        This ensures the Hit object is properly initialized with mandatory fields.
        """
        # Handle None alert_data
        if alert_data is None:
            alert_data = {}
            
        # Prepare hit data with required howler fields
        analytic_name = alert_data.get("alertDisplayName") or "Sentinel Alert"
        # Ensure analytic name is not empty (ODM validation requirement)
        if not analytic_name or not analytic_name.strip():
            analytic_name = "Sentinel Alert"
            
        hit_data = {
            'howler': {
                'id': str(uuid.uuid4()),
                'analytic': analytic_name,
                'hash': self._generate_hash(alert_data)
            }
        }
        
        return Hit(hit_data)
    
    def _generate_hash(self, alert_data: Dict[str, Any]) -> str:
        """Generate a hash for the hit based on alert data."""
        import hashlib
        
        # Handle None alert_data
        if alert_data is None:
            alert_data = {}
        
        # Use alert ID if available, otherwise generate from content
        alert_id = alert_data.get("systemAlertId", alert_data.get("id"))
        if alert_id:
            return hashlib.sha256(str(alert_id).encode()).hexdigest()
        
        # Generate hash from alert content
        content = str(alert_data.get("alertDisplayName", "")) + str(alert_data.get("description", ""))
        if content.strip():
            return hashlib.sha256(content.encode()).hexdigest()
        else:
            # For empty alerts, generate a hash from a default string
            return hashlib.sha256("empty_alert".encode()).hexdigest()
    
    def _map_alert_metadata(self, alert_data: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map basic alert metadata to hit fields.
        
        This consolidates the alert-level field mapping that was previously
        scattered across multiple methods.
        """
        # Update howler fields (howler object already exists from _create_base_hit)
        detection = alert_data.get("alertDisplayName", "Unknown Detection")
        if hasattr(hit.howler, 'detection') or detection != "Unknown Detection":
            hit.howler.detection = detection
        
        # Map alert timestamps
        created_time = alert_data.get("createdDateTime")
        if created_time:
            try:
                # Parse and set timestamp
                hit.timestamp = self._parse_timestamp(created_time)
            except Exception as e:
                self.logger.warning("Failed to parse timestamp %s: %s", created_time, str(e))
        
        # Map severity
        severity_raw = alert_data.get("severity", "")
        # Ensure severity is a string before calling .lower()
        if isinstance(severity_raw, str):
            severity = severity_raw.lower()
        else:
            severity = str(severity_raw).lower() if severity_raw else ""
            
        severity_mapping = {
            "high": 4,
            "medium": 3, 
            "low": 2,
            "informational": 1
        }
        hit.howler.score = severity_mapping.get(severity, 2)
        
        # Map MITRE ATT&CK data
        tactics = alert_data.get("tactics", [])
        techniques = alert_data.get("techniques", [])
        
        if tactics or techniques:
            if not hasattr(hit, 'tags') or not hit.tags:
                hit.tags = []
            
            for tactic in tactics:
                hit.tags.append(f"mitre:tactic:{tactic.lower()}")
            
            for technique in techniques:
                hit.tags.append(f"mitre:technique:{technique}")
        
        # Add general alert tags
        if not hasattr(hit, 'tags') or not hit.tags:
            hit.tags = []
        hit.tags.extend([
            "source:sentinel",
            f"severity:{severity}" if severity else "severity:unknown"
        ])
        
        # Store original alert ID for reference
        system_alert_id = alert_data.get("systemAlertId")
        if system_alert_id:
            hit.tags.append(f"alert_id:{system_alert_id}")
        
        return hit
    
    def _parse_timestamp(self, timestamp_str: str) -> str:
        """
        Parse timestamp string to ISO format.
        
        Handles various timestamp formats from Sentinel alerts.
        """
        try:
            # Try parsing as ISO format first
            if "T" in timestamp_str:
                dt = datetime.fromisoformat(timestamp_str.replace("Z", "+00:00"))
                return dt.isoformat()
            else:
                # Handle other formats as needed
                return timestamp_str
        except Exception:
            # Return as-is if parsing fails
            return timestamp_str
    
    def _hit_to_dict(self, hit: Hit) -> Dict[str, Any]:
        """
        Convert Hit object to dictionary.
        
        This is a simplified version that extracts the key fields
        needed for the hit service.
        """
        hit_dict = {}
        
        # Add all non-None attributes from hit
        for attr_name in dir(hit):
            if not attr_name.startswith('_'):
                attr_value = getattr(hit, attr_name, None)
                if attr_value is not None and not callable(attr_value):
                    hit_dict[attr_name] = attr_value
        
        return hit_dict
    
    def _create_minimal_hit(self, alert_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Create minimal hit data when mapping fails.
        
        This ensures we always return something usable even on errors.
        """
        # Handle None alert_data
        if alert_data is None:
            alert_data = {}
            
        return {
            "howler": {
                "id": str(uuid.uuid4()),
                "analytic": alert_data.get("alertDisplayName", "Sentinel Alert"),
                "detection": alert_data.get("alertDisplayName", "Unknown Detection"),
                "hash": self._generate_hash(alert_data),
                "score": 2
            },
            "tags": [
                "source:sentinel",
                "mapping:error"
            ],
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
