# Generated by GitHub Copilot – follow project guidelines above
"""
URL evidence mapper for transforming Sentinel URL evidence to ECS URL fields.
"""

from typing import Any, Dict, Optional
from urllib.parse import urlparse

from howler.common.exceptions import HowlerKeyError
from howler.odm.models.hit import Hit
from howler.odm.models.ecs.url import URL

from .base import BaseMapper, MappingError


class UrlEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel URL evidence to ECS URL fields.
    
    URL evidence contains information about URLs involved in alerts,
    including domain extraction and URL categorization.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map URL evidence to ECS URL fields.
        
        Args:
            evidence: URL evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with URL information
            
        Raises:
            MappingError: If critical URL data is missing or invalid
        """
        try:
            # Extract URL information
            url = self.safe_get(evidence, 'url')
            
            if not url:
                raise MappingError("URL evidence missing required url field")
            
            # Create or update URL information
            try:
                if not hit.url:
                    hit.url = URL()
            except (AttributeError, HowlerKeyError):
                hit.url = URL()
            
            # Set URL fields
            hit.url.full = url
            
            # Parse URL for additional fields
            try:
                parsed_url = urlparse(url)
                
                if parsed_url.scheme:
                    hit.url.scheme = parsed_url.scheme
                
                if parsed_url.netloc:
                    hit.url.domain = parsed_url.netloc
                    
                if parsed_url.path:
                    hit.url.path = parsed_url.path
                    
                if parsed_url.query:
                    hit.url.query = parsed_url.query
                    
                if parsed_url.fragment:
                    hit.url.fragment = parsed_url.fragment
                    
                # Set port if available
                if parsed_url.port:
                    hit.url.port = parsed_url.port
                    
            except Exception as e:
                self.logger.warning("Failed to parse URL %s: %s", url, str(e))
            
            # Add URL metadata
            self._add_url_metadata(evidence, hit, url)
            
            self.logger.debug(
                "Successfully mapped URL evidence: %s",
                url[:100] + "..." if len(url) > 100 else url
            )
            
            return hit
            
        except Exception as e:
            if isinstance(e, MappingError):
                raise
            raise MappingError(f"Failed to map URL evidence: {str(e)}") from e
    
    def _add_url_metadata(
        self, 
        evidence: Dict[str, Any], 
        hit: Hit, 
        url: str
    ) -> None:
        """
        Add URL-specific metadata to the hit.
        
        Args:
            evidence: Original URL evidence data
            hit: Hit object to update
            url: URL string
        """
        # Add URL tags
        if not hit.tags:
            hit.tags = []
        
        # Tag for URL activity
        if "url:accessed" not in hit.tags:
            hit.tags.append("url:accessed")
        
        # Add domain-based tags
        try:
            parsed_url = urlparse(url)
            if parsed_url.netloc:
                domain_tag = f"url:domain:{parsed_url.netloc}"
                if domain_tag not in hit.tags:
                    hit.tags.append(domain_tag)
                    
                # Add scheme tag
                if parsed_url.scheme:
                    scheme_tag = f"url:scheme:{parsed_url.scheme}"
                    if scheme_tag not in hit.tags:
                        hit.tags.append(scheme_tag)
        except Exception as e:
            self.logger.warning("Failed to parse URL for tagging: %s", str(e))
        
        # Add verdict-based tags
        verdict = self.safe_get(evidence, 'verdict')
        if verdict:
            verdict_tag = f"url:verdict:{verdict}"
            if verdict_tag not in hit.tags:
                hit.tags.append(verdict_tag)
        
        # Store raw evidence data for analysis
        if not hasattr(hit, '_evidence_metadata'):
            hit._evidence_metadata = {}
        
        hit._evidence_metadata['url_evidence'] = {
            'url': url,
            'verdict': verdict,
            'remediation_status': self.safe_get(evidence, 'remediationStatus'),
            'roles': self.safe_get(evidence, 'roles', []),
            'tags': self.safe_get(evidence, 'tags', [])
        }
