# Generated by GitHub Copilot – follow project guidelines above
"""
User evidence mapper for transforming Sentinel user evidence to ECS user fields.
"""

from typing import Any, Dict, Optional

from howler.common.exceptions import HowlerKeyError
from howler.odm.models.hit import Hit
from howler.odm.models.ecs.user import User

from .base import BaseMapper, MappingError


class UserEvidenceMapper(BaseMapper):
    """
    Maps Microsoft Sentinel user evidence to ECS user fields.
    
    User evidence contains information about users involved in the alert,
    including account names, domains, and user identifiers.
    
    Note: When multiple user evidence items exist, this mapper implements
    a consolidation strategy where user information is merged to create
    a comprehensive user profile.
    """
    
    def map(self, evidence: Dict[str, Any], hit: Hit) -> Hit:
        """
        Map user evidence to ECS user fields.
        
        Args:
            evidence: User evidence from Sentinel alert
            hit: Hit object to populate
            
        Returns:
            Updated hit with user information
            
        Raises:
            MappingError: If critical user data is missing or invalid
        """
        try:
            # Extract user account information
            user_account = self.safe_get(evidence, 'userAccount')
            if not user_account:
                raise MappingError("User evidence missing userAccount data")
            
            account_name = self.safe_get(user_account, 'accountName')
            if not account_name:
                raise MappingError("User evidence missing account name")
            
            # Create or enhance user information
            try:
                if not hit.user:
                    hit.user = self._create_primary_user(user_account)
                    self.logger.debug("Created primary user: %s", account_name)
                else:
                    self._enhance_existing_user(user_account, hit)
                    self.logger.debug("Enhanced existing user with additional data: %s", account_name)
            except (AttributeError, HowlerKeyError):
                hit.user = self._create_primary_user(user_account)
                self.logger.debug("Created primary user: %s", account_name)
            
            return hit
            
        except Exception as e:
            self.logger.error("Failed to map user evidence: %s", str(e))
            raise MappingError(f"User evidence mapping failed: {str(e)}") from e
    
    def _create_primary_user(self, user_account: Dict[str, Any]) -> User:
        """
        Create primary user from user account data.
        
        Args:
            user_account: User account information
            
        Returns:
            Populated User object
        """
        user = User()
        
        # Basic user identification
        account_name = self.safe_get(user_account, 'accountName')
        if account_name:
            user.name = account_name
        
        # Domain information
        domain_name = self.safe_get(user_account, 'domainName')
        if domain_name:
            user.domain = domain_name
        
        # User identifiers
        user_sid = self.safe_get(user_account, 'userSid')
        if user_sid:
            user.id = user_sid
        
        azure_ad_user_id = self.safe_get(user_account, 'azureAdUserId')
        if azure_ad_user_id and not user.id:
            user.id = azure_ad_user_id
        
        # Principal name and display name
        user_principal_name = self.safe_get(user_account, 'userPrincipalName')
        if user_principal_name:
            user.email = user_principal_name  # UPN often serves as email
        
        display_name = self.safe_get(user_account, 'displayName')
        if display_name:
            user.full_name = display_name
        
        return user
    
    def _enhance_existing_user(self, user_account: Dict[str, Any], hit: Hit) -> None:
        """
        Enhance existing user with additional account data.
        
        This method handles many-to-one mapping where multiple user evidence
        items contribute to a single ECS user field.
        
        Args:
            user_account: Additional user account information
            hit: Hit object with existing user data
        """
        # Merge domain information (prefer non-null values)
        domain_name = self.safe_get(user_account, 'domainName')
        if domain_name and not hit.user.domain:
            hit.user.domain = domain_name
        
        # Merge user identifiers
        user_sid = self.safe_get(user_account, 'userSid')
        if user_sid and not hit.user.id:
            hit.user.id = user_sid
        
        azure_ad_user_id = self.safe_get(user_account, 'azureAdUserId')
        if azure_ad_user_id and not hit.user.id:
            hit.user.id = azure_ad_user_id
        
        # Merge email/UPN information
        user_principal_name = self.safe_get(user_account, 'userPrincipalName')
        if user_principal_name and not hit.user.email:
            hit.user.email = user_principal_name
        
        # Merge display name
        display_name = self.safe_get(user_account, 'displayName')
        if display_name and not hit.user.full_name:
            hit.user.full_name = display_name
        
        # Validate consistency of account names
        account_name = self.safe_get(user_account, 'accountName')
        if account_name and hit.user.name and account_name != hit.user.name:
            self.logger.warning(
                "Inconsistent account names in user evidence: existing=%s, new=%s",
                hit.user.name,
                account_name
            )
    
    def _validate_user_consistency(self, existing_user: User, new_account: Dict[str, Any]) -> bool:
        """
        Validate that new user account data is consistent with existing user.
        
        Args:
            existing_user: Existing user object
            new_account: New user account data
            
        Returns:
            True if data is consistent or can be merged
        """
        account_name = self.safe_get(new_account, 'accountName')
        
        # If names are provided, they should match
        if (existing_user.name and account_name and 
            existing_user.name.lower() != account_name.lower()):
            self.logger.warning(
                "User name mismatch: existing=%s, new=%s",
                existing_user.name,
                account_name
            )
            return False
        
        # Additional consistency checks could be added here
        # For example, domain validation, SID validation, etc.
        
        return True
