# Generated by GitHub Copilot – follow project guidelines above
"""
Simple test script to verify the unified mapper implementation.
"""

import json
from typing import Any, Dict

# Mock the required modules for testing
class MockHit:
    def __init__(self):
        pass

class MockHost:
    def __init__(self):
        self.id = None
        self.hostname = None
        self.name = None
        self.os = None

class MockProcess:
    def __init__(self):
        self.command_line = None
        self.pid = None
        self.name = None
        self.parent = None

class MockUser:
    def __init__(self):
        self.id = None
        self.email = None
        self.name = None
        self.domain = None
        self.full_name = None

class MockLogger:
    def debug(self, msg, *args):
        print(f"DEBUG: {msg % args if args else msg}")
    
    def info(self, msg, *args):
        print(f"INFO: {msg % args if args else msg}")
    
    def warning(self, msg, *args):
        print(f"WARNING: {msg % args if args else msg}")
    
    def error(self, msg, *args, **kwargs):
        print(f"ERROR: {msg % args if args else msg}")

def test_evidence_type_detection():
    """Test evidence type detection logic."""
    print("Testing evidence type detection...")
    
    # Mock the unified mapper class for testing
    class TestUnifiedMapper:
        def __init__(self):
            self.logger = MockLogger()
            
        def _detect_evidence_type(self, evidence: Dict[str, Any]) -> str:
            """Detect evidence type from evidence data structure."""
            # Check @odata.type if available
            odata_type = evidence.get("@odata.type", "")
            if "deviceEvidence" in odata_type.lower():
                return "device"
            elif "processEvidence" in odata_type.lower():
                return "process"
            elif "userEvidence" in odata_type.lower():
                return "user"
            elif "fileEvidence" in odata_type.lower():
                return "file"
            elif "ipEvidence" in odata_type.lower():
                return "ip"
            elif "urlEvidence" in odata_type.lower():
                return "url"
            elif "registryKeyEvidence" in odata_type.lower():
                return "registry_key"
            elif "registryValueEvidence" in odata_type.lower():
                return "registry_value"
            elif "cloudApplicationEvidence" in odata_type.lower():
                return "cloud_app"
            elif "oAuthApplicationEvidence" in odata_type.lower():
                return "oauth_app"
                
            # Fallback to data structure analysis
            if "deviceId" in evidence or "hostname" in evidence:
                return "device"
            elif "processId" in evidence or "commandLine" in evidence:
                return "process"
            elif "userId" in evidence or "userPrincipalName" in evidence:
                return "user"
            elif "fileName" in evidence or "fileHash" in evidence:
                return "file"
            elif "ipAddress" in evidence:
                return "ip"
            elif "url" in evidence:
                return "url"
            elif "registryKey" in evidence and "registryValue" not in evidence:
                return "registry_key"
            elif "registryValue" in evidence:
                return "registry_value"
            elif "appId" in evidence and "publisher" not in evidence:
                return "cloud_app"
            elif "appId" in evidence and "publisher" in evidence:
                return "oauth_app"
                
            return "unknown"
    
    mapper = TestUnifiedMapper()
    
    # Test cases
    test_cases = [
        {
            "evidence": {"@odata.type": "#Microsoft.SecurityInsights.DeviceEvidence", "deviceId": "123"},
            "expected": "device"
        },
        {
            "evidence": {"processId": 1234, "commandLine": "cmd.exe"},
            "expected": "process"
        },
        {
            "evidence": {"userPrincipalName": "user@domain.com"},
            "expected": "user"
        },
        {
            "evidence": {"fileName": "malware.exe"},
            "expected": "file"
        },
        {
            "evidence": {"ipAddress": "192.168.1.1"},
            "expected": "ip"
        },
        {
            "evidence": {"url": "https://malicious.com"},
            "expected": "url"
        },
        {
            "evidence": {"registryKey": "HKLM\\Software\\Test"},
            "expected": "registry_key"
        },
        {
            "evidence": {"registryKey": "HKLM\\Software\\Test", "registryValue": "malicious"},
            "expected": "registry_value"
        },
        {
            "evidence": {"appId": "app123", "displayName": "Test App"},
            "expected": "cloud_app"
        },
        {
            "evidence": {"appId": "app123", "publisher": "Microsoft"},
            "expected": "oauth_app"
        }
    ]
    
    passed = 0
    total = len(test_cases)
    
    for i, test_case in enumerate(test_cases, 1):
        result = mapper._detect_evidence_type(test_case["evidence"])
        expected = test_case["expected"]
        
        if result == expected:
            print(f"✓ Test {i}: {expected} - PASSED")
            passed += 1
        else:
            print(f"✗ Test {i}: Expected {expected}, got {result} - FAILED")
    
    print(f"\nResults: {passed}/{total} tests passed")
    return passed == total

def test_simplified_mapping():
    """Test simplified mapping approach."""
    print("\nTesting simplified mapping approach...")
    
    # Sample Sentinel alert data
    sample_alert = {
        "systemAlertId": "test-alert-123",
        "alertDisplayName": "Suspicious Process Execution",
        "description": "Detected suspicious process activity",
        "severity": "High",
        "status": "New",
        "createdDateTime": "2025-05-30T10:00:00Z",
        "tactics": ["InitialAccess", "Execution"],
        "techniques": ["T1566.001", "T1059"],
        "evidence": [
            {
                "@odata.type": "#Microsoft.SecurityInsights.DeviceEvidence",
                "deviceId": "device-123",
                "hostname": "workstation-01",
                "osPlatform": "Windows"
            },
            {
                "@odata.type": "#Microsoft.SecurityInsights.ProcessEvidence",
                "processId": 1234,
                "commandLine": "powershell.exe -enc <base64>",
                "processName": "powershell.exe"
            },
            {
                "@odata.type": "#Microsoft.SecurityInsights.UserEvidence",
                "userId": "user-456",
                "userPrincipalName": "john.doe@company.com",
                "displayName": "John Doe"
            }
        ]
    }
    
    print("Sample alert structure:")
    print(f"- Alert: {sample_alert['alertDisplayName']}")
    print(f"- Severity: {sample_alert['severity']}")
    print(f"- Evidence items: {len(sample_alert['evidence'])}")
    
    for i, evidence in enumerate(sample_alert['evidence'], 1):
        evidence_type = evidence.get('@odata.type', 'Unknown')
        print(f"  {i}. {evidence_type}")
    
    print("\n✓ Simplified mapping structure validated")
    return True

if __name__ == "__main__":
    print("=== Unified Mapper Implementation Test ===\n")
    
    test1_passed = test_evidence_type_detection()
    test2_passed = test_simplified_mapping()
    
    print(f"\n=== Summary ===")
    print(f"Evidence type detection: {'PASSED' if test1_passed else 'FAILED'}")
    print(f"Simplified mapping: {'PASSED' if test2_passed else 'FAILED'}")
    
    if test1_passed and test2_passed:
        print("\n🎉 All tests passed! Implementation is ready.")
    else:
        print("\n❌ Some tests failed. Review implementation.")
