# Generated by GitHub Copilot – follow project guidelines above
from typing import Any, Dict, Optional

from flask import request
from howler.api import bad_request, created, make_subapi_blueprint, ok
from howler.common.exceptions import HowlerException
from howler.common.logging import get_logger
from howler.common.swagger import generate_swagger_docs
from howler.datastore import datastore
from howler.security import api_login
from howler.services import analytic_service, hit_service
from howler.odm.models.user import User

from ..mappers.alert import SentinelAlertMapper

SUB_API = "sentinel"
sentinel_api = make_subapi_blueprint(SUB_API, api_version=1)
sentinel_api._doc = "Interact with Microsoft Sentinel alerts"

logger = get_logger(__file__)


@generate_swagger_docs()
@sentinel_api.route("/ingest", methods=["POST"])
@api_login(required_priv=["W"])
def ingest_alert(user: User, **kwargs) -> Dict[str, Any]:
    """Ingest a Microsoft Sentinel alert into Howler as a Hit.
    
    This endpoint processes Microsoft Sentinel alerts with complex evidence structures,
    maps them to ECS (Elastic Common Schema) format, and creates corresponding Hit records
    in the Howler system for security analysis and tracking.

    Variables:
    None

    Optional Arguments:
    ignore_extra_values (bool): Whether to ignore unmapped alert fields. Defaults to True.

    Data Block:
    {
        "systemAlertId": "...",
        "alertDisplayName": "...",
        "description": "...",
        "severity": "High|Medium|Low|Informational",
        "status": "New|InProgress|Resolved",
        "tactics": ["InitialAccess", "Persistence", ...],
        "techniques": ["T1566.001", "T1078", ...],
        "evidence": [
            {
                "@odata.type": "#Microsoft.SecurityInsights.DeviceEvidence",
                "deviceId": "...",
                "deviceName": "...",
                ...
            },
            ...
        ],
        ...
    }

    Result Example:
    {
        "hit_id": "generated-hit-uuid",
        "success": true,
        "warnings": ["field X was not mapped", ...]
    }
    """
    try:
        # Validate request data
        sentinel_alert = request.json
        if not sentinel_alert:
            return bad_request(err="No alert data provided")

        # Extract optional parameters
        ignore_extra_values: bool = request.args.get(
            "ignore_extra_values", "true", type=lambda v: v.lower() == "true"
        )

        logger.info(
            "Processing Sentinel alert: %s (severity: %s, status: %s)",
            sentinel_alert.get("alertDisplayName", "Unknown"),
            sentinel_alert.get("severity", "Unknown"),
            sentinel_alert.get("status", "Unknown")
        )

        # Initialize the alert mapper and process the alert
        alert_mapper = SentinelAlertMapper()
        mapped_hit_data, mapping_warnings = alert_mapper.map_alert(sentinel_alert)

        logger.debug("Mapped hit data: %s", mapped_hit_data)
        logger.debug("Mapping warnings: %s", mapping_warnings)

        # Convert the mapped data to a Hit ODM object
        hit_odm, conversion_warnings = hit_service.convert_hit(
            mapped_hit_data, 
            unique=True, 
            ignore_extra_values=ignore_extra_values
        )

        # Combine all warnings
        all_warnings = mapping_warnings + conversion_warnings

        # Ensure event ID matches hit ID
        if hit_odm.event:
            hit_odm.event.id = hit_odm.howler.id

        # Create the hit in the database
        hit_service.create_hit(hit_odm.howler.id, hit_odm, user=user["uname"])
        
        # Save analytics information
        analytic_service.save_from_hit(hit_odm, user)

        # Commit changes to datastore
        datastore().hit.commit()

        logger.info(
            "Successfully ingested Sentinel alert as Hit: %s (analytic: %s)",
            hit_odm.howler.id,
            hit_odm.howler.analytic
        )

        response_data = {
            "hit_id": hit_odm.howler.id,
            "success": True,
            "analytic": hit_odm.howler.analytic,
            "evidence_count": len(sentinel_alert.get("evidence", [])),
            "mapped_fields": len(mapped_hit_data),
        }

        if all_warnings:
            response_data["warnings"] = all_warnings
            logger.warning("Ingestion warnings for alert %s: %s", 
                         sentinel_alert.get("systemAlertId", "unknown"), all_warnings)

        return created(response_data, warnings=all_warnings)

    except HowlerException as e:
        logger.error("Howler error processing Sentinel alert: %s", str(e))
        return bad_request(err=f"Processing error: {str(e)}")
    
    except Exception as e:
        logger.exception("Unexpected error processing Sentinel alert: %s", str(e))
        return bad_request(err=f"Unexpected error: {str(e)}")


@generate_swagger_docs()
@sentinel_api.route("/health", methods=["GET"])
def health_check() -> Dict[str, Any]:
    """Health check endpoint for the Sentinel plugin.
    
    Variables:
    None

    Optional Arguments:
    None

    Result Example:
    {
        "status": "healthy",
        "plugin": "sentinel",
        "mappers": ["alert", "device", "process", "user", "file"]
    }
    """
    try:
        # Test mapper initialization to ensure dependencies are working
        SentinelAlertMapper()
        
        return ok({
            "status": "healthy",
            "plugin": "sentinel",
            "version": "1.0.0",
            "mappers": ["alert", "device", "process", "user", "file"],
            "description": "Microsoft Sentinel to Howler ECS mapping service"
        })
    except Exception as e:
        logger.exception("Health check failed: %s", str(e))
        return bad_request(err=f"Health check failed: {str(e)}")
