# Generated by GitHub Copilot – follow project guidelines above
"""
Comprehensive test for Sentinel plugin resilience against unexpected data.

This test module validates that the Sentinel plugin handles malformed,
missing, and unexpected data gracefully without breaking the processing pipeline.
"""

import json
import pytest
from typing import Any, Dict, List

from sentinel.mappers.alert import SentinelAlertMapper


class TestSentinelDataResilience:
    """Test suite for validating Sentinel plugin data resilience."""
    
    def setup_method(self) -> None:
        """Set up test environment."""
        self.mapper = SentinelAlertMapper()
    
    def test_empty_alert(self) -> None:
        """Test handling of completely empty alert."""
        empty_alert = {}
        
        hit, warnings = self.mapper.map_alert(empty_alert)
        
        # Should not crash and should produce warnings
        assert hit is not None
        assert len(warnings) > 0
        assert any("unknown" in warning.lower() for warning in warnings)
    
    def test_null_fields(self) -> None:
        """Test handling of null/None fields."""
        alert_with_nulls = {
            "id": None,
            "alertDisplayName": None,
            "description": None,
            "severity": None,
            "evidence": None
        }
        
        hit, warnings = self.mapper.map_alert(alert_with_nulls)
        
        assert hit is not None
        assert len(warnings) > 0
    
    def test_wrong_data_types(self) -> None:
        """Test handling of incorrect data types."""
        alert_with_wrong_types = {
            "id": 12345,  # Should be string
            "alertDisplayName": ["list", "instead", "of", "string"],  # Should be string
            "description": {"nested": "object"},  # Should be string
            "severity": 42.5,  # Should be string
            "evidence": "not_a_list"  # Should be list
        }
        
        hit, warnings = self.mapper.map_alert(alert_with_wrong_types)
        
        assert hit is not None
        assert len(warnings) > 0
    
    def test_malformed_evidence(self) -> None:
        """Test handling of malformed evidence items."""
        alert_with_bad_evidence = {
            "id": "test-alert-123",
            "alertDisplayName": "Test Alert",
            "evidence": [
                None,  # Null evidence item
                "string_instead_of_dict",  # Wrong type
                {},  # Empty dict
                {"@odata.type": None},  # Null odata type
                {"@odata.type": ""},  # Empty odata type
                {"@odata.type": 12345},  # Wrong type for odata
                {"@odata.type": "#unknown.type"},  # Unknown type
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "malformed": "data with unexpected fields"
                },
                {
                    "@odata.type": "#microsoft.graph.security.ipEvidence",
                    "ipAddress": "not.an.ip.address"  # Invalid IP
                },
                {
                    "@odata.type": "#microsoft.graph.security.fileEvidence",
                    "fileName": None,
                    "sha256": "invalid_hash"  # Invalid hash format
                }
            ]
        }
        
        hit, warnings = self.mapper.map_alert(alert_with_bad_evidence)
        
        assert hit is not None
        # Should have warnings for each problematic evidence item
        assert len(warnings) >= 5
    
    def test_circular_references(self) -> None:
        """Test handling of circular references in data."""
        # Create circular reference
        circular_data = {"id": "test"}
        circular_data["self_ref"] = circular_data
        
        alert_with_circular = {
            "id": "test-alert-456",
            "alertDisplayName": "Circular Test",
            "evidence": [
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "circular": circular_data
                }
            ]
        }
        
        # This should not cause infinite recursion
        hit, warnings = self.mapper.map_alert(alert_with_circular)
        
        assert hit is not None
    
    def test_extremely_large_data(self) -> None:
        """Test handling of extremely large data structures."""
        large_string = "x" * 1000000  # 1MB string
        large_list = ["item"] * 10000  # 10k items
        
        alert_with_large_data = {
            "id": "test-alert-789",
            "alertDisplayName": large_string,
            "description": large_string,
            "evidence": [
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "deviceDnsName": large_string,
                    "largeList": large_list
                }
            ]
        }
        
        hit, warnings = self.mapper.map_alert(alert_with_large_data)
        
        assert hit is not None
    
    def test_unicode_and_special_characters(self) -> None:
        """Test handling of unicode and special characters."""
        alert_with_unicode = {
            "id": "test-alert-unicode",
            "alertDisplayName": "Test Alert 🚨 with émojis and spëcial çhars",
            "description": "Description with\nnewlines\tand\ttabs\rand\rcarriage\x00returns\x01",
            "evidence": [
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "deviceDnsName": "host-名前.example.com",
                    "hostName": "💻-host"
                },
                {
                    "@odata.type": "#microsoft.graph.security.ipEvidence",
                    "ipAddress": "192.168.1.1",
                    "countryCode": "🇺🇸"  # Emoji country code
                }
            ]
        }
        
        hit, warnings = self.mapper.map_alert(alert_with_unicode)
        
        assert hit is not None
    
    def test_deeply_nested_structures(self) -> None:
        """Test handling of deeply nested data structures."""
        def create_nested_dict(depth: int) -> Dict[str, Any]:
            if depth <= 0:
                return {"value": "deep"}
            return {"nested": create_nested_dict(depth - 1)}
        
        deep_structure = create_nested_dict(100)  # 100 levels deep
        
        alert_with_deep_nesting = {
            "id": "test-alert-deep",
            "alertDisplayName": "Deep Nesting Test",
            "evidence": [
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "deepData": deep_structure
                }
            ]
        }
        
        hit, warnings = self.mapper.map_alert(alert_with_deep_nesting)
        
        assert hit is not None
    
    def test_invalid_json_like_strings(self) -> None:
        """Test handling of strings that look like JSON but aren't."""
        alert_with_json_strings = {
            "id": "test-alert-json",
            "alertDisplayName": '{"not": "real json"',  # Malformed JSON string
            "description": "[1,2,3,4,5",  # Incomplete JSON array
            "evidence": [
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "deviceDnsName": '{"hostname": "test"}',  # JSON string in wrong field
                }
            ]
        }
        
        hit, warnings = self.mapper.map_alert(alert_with_json_strings)
        
        assert hit is not None
    
    def test_boundary_values(self) -> None:
        """Test handling of boundary values."""
        alert_with_boundaries = {
            "id": "",  # Empty string
            "alertDisplayName": " ",  # Whitespace only
            "severity": "0",  # Boundary number as string
            "evidence": [
                {
                    "@odata.type": "#microsoft.graph.security.ipEvidence",
                    "ipAddress": "0.0.0.0"  # Boundary IP address
                },
                {
                    "@odata.type": "#microsoft.graph.security.ipEvidence",
                    "ipAddress": "255.255.255.255"  # Max IP address
                }
            ]
        }
        
        hit, warnings = self.mapper.map_alert(alert_with_boundaries)
        
        assert hit is not None
    
    def test_memory_exhaustion_protection(self) -> None:
        """Test protection against memory exhaustion attacks."""
        # Create a structure that could potentially cause memory issues
        large_dict = {}
        for i in range(10000):
            large_dict[f"key_{i}"] = f"value_{i}" * 100
        
        alert_memory_test = {
            "id": "memory-test",
            "alertDisplayName": "Memory Test",
            "evidence": [
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "largeData": large_dict
                }
            ] * 100  # 100 evidence items with large data
        }
        
        hit, warnings = self.mapper.map_alert(alert_memory_test)
        
        assert hit is not None
    
    def test_mixed_valid_invalid_evidence(self) -> None:
        """Test processing mix of valid and invalid evidence."""
        alert_mixed = {
            "id": "mixed-test",
            "alertDisplayName": "Mixed Evidence Test",
            "evidence": [
                # Valid evidence
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "deviceDnsName": "valid-host.example.com"
                },
                # Invalid evidence
                {
                    "@odata.type": "#microsoft.graph.security.deviceEvidence",
                    "deviceDnsName": None
                },
                # Valid evidence
                {
                    "@odata.type": "#microsoft.graph.security.ipEvidence",
                    "ipAddress": "192.168.1.100"
                },
                # Invalid evidence
                {
                    "@odata.type": "#microsoft.graph.security.ipEvidence",
                    "ipAddress": "not-an-ip"
                },
                # Unknown evidence type
                {
                    "@odata.type": "#microsoft.graph.security.unknownEvidence",
                    "someField": "someValue"
                }
            ]
        }
        
        hit, warnings = self.mapper.map_alert(alert_mixed)
        
        assert hit is not None
        # Should have processed valid evidence and warned about invalid
        assert len(warnings) >= 2  # At least 2 invalid items
        
        # Check that valid evidence was actually processed
        assert hit.get('host') is not None
        assert hit['host']['name'] == "valid-host.example.com"
        assert hit['host'].get('ip') is not None
        assert "192.168.1.100" in hit['host']['ip']


def test_malformed_json_input() -> None:
    """Test that the system handles malformed JSON gracefully."""
    mapper = SentinelAlertMapper()

    # Test with various malformed inputs that might come from external sources
    malformed_inputs = [
        None,
        "",
        "not json",
        '{"incomplete": json',
        '{"valid": "json", "but": ["unexpected", "structure]}',
        42,
        [],
        True,
        {"completely": {"unexpected": {"structure": True}}}
    ]

    for malformed_input in malformed_inputs:
        hit, warnings = mapper.map_alert(malformed_input)
        assert hit is not None, f"Hit should not be None for input: {malformed_input}"
        assert isinstance(warnings, list), f"Warnings should be a list for input: {malformed_input}"
        assert len(warnings) > 0, f"Warnings should not be empty for input: {malformed_input}"
        assert any("Invalid alert data type" in warning or "Alert ID is None" in warning for warning in warnings), (
            f"Expected warning message not found for input: {malformed_input}"
        )


if __name__ == "__main__":
    # Run basic tests for quick validation
    test_instance = TestSentinelDataResilience()
    test_instance.setup_method()
    
    print("Running resilience tests...")
    
    try:
        test_instance.test_empty_alert()
        print("✓ Empty alert test passed")
        
        test_instance.test_null_fields()
        print("✓ Null fields test passed")
        
        test_instance.test_malformed_evidence()
        print("✓ Malformed evidence test passed")
        
        test_instance.test_mixed_valid_invalid_evidence()
        print("✓ Mixed evidence test passed")
        
        print("All basic resilience tests passed!")
        
    except Exception as e:
        print(f"❌ Test failed: {e}")
        raise
